// Regenerates src/abi.generated.ts from Foundry's build output, so the API decodes calls, events and custom errors
// against exactly what was compiled and deployed. Run `forge build` at the repo root first, then `pnpm --filter api abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const artifacts = {
  glanceVaultAbi: "GlanceVault.sol/GlanceVault.json",
  glanceVaultFactoryAbi: "GlanceVaultFactory.sol/GlanceVaultFactory.json",
  stockDeskAbi: "StockDesk.sol/StockDesk.json",
  testPriceFeedAbi: "TestPriceFeed.sol/TestPriceFeed.json",
  testUsdgAbi: "TestUSDG.sol/TestUSDG.json",
  erc20Abi: "IERC20Metadata.sol/IERC20Metadata.json",
  erc20ErrorsAbi: "draft-IERC6093.sol/IERC20Errors.json",
};

let out = "// Generated by scripts/gen-abi.mjs from Foundry artifacts in out/. Do not edit by hand.\n\n";
for (const [name, path] of Object.entries(artifacts)) {
  const { abi } = JSON.parse(readFileSync(resolve(root, "out", path), "utf8"));
  out += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(resolve(root, "apps/api/src/abi.generated.ts"), out);
console.log(`wrote apps/api/src/abi.generated.ts (${Object.keys(artifacts).length} ABIs)`);
